version: '3.3'

services:
    main:
        image: "${MAIN_IMAGE:-webrecorder/kubecaptures-main}:${MAIN_TAG:-latest}"
        build:
          context: ./main/
          args:
            BASE_IMAGE: "${MAIN_IMAGE_BASE:-webrecorder/browserkube-main}"

    driver:
        image: "${DRIVER_IMAGE:-webrecorder/kubecaptures-driver}:${DRIVER_TAG:-latest}"
        build:
          context: ./driver/
          args:
            BASE_IMAGE: "${DRIVER_IMAGE_BASE:-node:12.14}"
