version: '3.3'

services:
    permafact-backend:
        image: "${MAIN_IMAGE:-ikreymer/permaproof-main}:${MAIN_TAG:-dev}"
        build: ./main/

    driver:
        image: "${DRIVER_IMAGE:-ikreymer/permaproof-driver}:${DRIVER_TAG:-dev}"
        build: ./driver/
