version: '3.3'

services:
    permafact-backend:
        image: "${MAIN_IMAGE:-webrecorder/kubecaptures-main}:${MAIN_TAG:-latest}"
        build: ./main/

    driver:
        image: "${DRIVER_IMAGE:-webrecorder/kubecaptures-driver}:${DRIVER_TAG:-latest}"
        build: ./driver/
